

// actions/user.ts
export const REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL: 'REGISTER_USER_FAIL' = 'REGISTER_USER_FAIL';

export const AUTH_USER_REQUEST: 'AUTH_USER_REQUEST' = 'AUTH_USER_REQUEST';
export const AUTH_USER_SUCCESS: 'AUTH_USER_SUCCESS' = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAIL: 'AUTH_USER_FAIL' = 'AUTH_USER_FAIL';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAIL: 'GET_USER_FAIL' = 'GET_USER_FAIL';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL: 'UPDATE_USER_FAIL' = 'UPDATE_USER_FAIL';

export const LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL: 'LOGOUT_USER_FAIL' = 'LOGOUT_USER_FAIL';

// actions/profileModal.ts
export const PROFILE_MODAL_OPEN: 'PROFILE_MODAL_OPEN' = 'PROFILE_MODAL_OPEN';
export const PROFILE_MODAL_CLOSE: 'PROFILE_MODAL_CLOSE' = 'PROFILE_MODAL_CLOSE';

// actions/priceItems.ts
export const GET_PRICEITEMS_REQUEST: 'GET_PRICEITEMS_REQUEST' = 'GET_PRICEITEMS_REQUEST';
export const GET_PRICEITEMS_SUCCESS: 'GET_PRICEITEMS_SUCCESS' = 'GET_PRICEITEMS_SUCCESS';
export const GET_PRICEITEMS_FAIL: 'GET_PRICEITEMS_FAIL' = 'GET_PRICEITEMS_FAIL';
